name: CI CD Test

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

     name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          rm gcp-key.json
      
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        
    - name: Prepare SSH directory
      run: mkdir -p ~/.ssh

     - name: Copy files to GCP VM
        run: |
          mkdir -p ~/.ssh
          echo "y" | gcloud compute scp --recurse ./ \
            tanmaymi251@ubuntu-4gb:~/test \
            --zone=us-central1-c \
            --ssh-key-expire-after=1h

            
    - name: Run remote deployment script
      run: |
        gcloud compute ssh tanmaymi251@ubuntu-4gb \
          --zone=us-central1-c \
          --command="cd ~/testCd && ./deploy.sh"
