name: CI CD Test

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
        
     
    - name: Authenticate to Google Cloud
      run: |
          echo "${{ secrets.SERVICE_ACCOUNT_KEY }}" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          rm gcp-key.json

    - name: Generate SSH key
      run: |
        ssh-keygen -t rsa -f ~/.ssh/google_compute_engine -C $USER -N ""

    - name: Prepare SSH directory
      run: mkdir -p ~/.ssh

    - name: Copy files to GCP VM
      run: |
        tar --exclude='.git' -czf app.tar.gz .
        gcloud compute scp app.tar.gz tanmaymi251@ubuntu-4gb:~/test --zone=us-central1-c
        gcloud compute ssh tanmaymi251@ubuntu-4gb --zone=us-central1-c --command="cd ~/test && tar -xzf app.tar.gz && rm app.tar.gz"


            
    - name: Run remote deployment script
      run: |
        gcloud compute ssh tanmaymi251@ubuntu-4gb \
          --zone=us-central1-c \
          --command="cd ~/testCd && ./deploy.sh"
